plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
}

group = project.maven_group
version = project.mod_version + "+" + project.minecraft_version

base {
    archivesName = project.archives_name
}

def generatedResources = file("src/generated/resources")

loom {
    silentMojangMappingsLicense()
    forge {
        mixinConfig 'alloyed.mixins.json'
    }
    runs {
        data {
            data()
            programArgs "--all", "--mod", "alloyed"
            programArgs "--output", generatedResources.absolutePath
        }
    }
    runs.configureEach {
        programArg("-mixin.config=create.mixins.json")
    }
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven { url = "https://maven.parchmentmc.org" } // Parchment mappings

    // mavens used on both forge and fabric
    maven { url = "https://maven.blamejared.com/" } // JEI
    maven { url = "https://maven.tterrag.com/" } // Registrate on forge
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.officialMojangMappings()
    forge "net.minecraftforge:forge:$project.forge_version"

    // Create and its dependencies
    modImplementation("com.simibubi.create:create-$minecraft_version:$create_version:slim") { transitive = false }
    modImplementation("com.tterrag.registrate:Registrate:$registrate_version")
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    modImplementation("maven.modrinth:farmers-delight:1.20.1-1.2.7")
    modImplementation("maven.modrinth:create-deco:2.0.3-1.20.1-forge")

    // Development QOL
    modLocalRuntime("mezz.jei:jei-$minecraft_version-forge:$jei_version") { transitive = false }

    // if you would like to add integration with JEI, uncomment this line.
//    modCompileOnly("mezz.jei:jei-$minecraft_version:$jei_version:api")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

// Configure Maven publishing.
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}