# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = forge

# Mod properties
mod_version = 2.0.1
maven_group = com.molybdenum.alloyed
archives_name = create_alloyed

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
forge_version = 1.20.1-47.4.0
create_version = 6.0.2-53
ponder_version = 1.0.51
flywheel_version = 1.0.1
registrate_version = MC1.20-1.3.3
emi_version = 1.1.18+1.20.1
jei_version = 15.20.0.106
