# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = forge

# Mod properties
mod_version = 1.6.0
maven_group = com.molybdenum.alloyed
archives_name = create_alloyed

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
forge_version = 1.20.1-47.3.22
create_version = 0.5.1.j-55
registrate_version = MC1.20-1.3.3
flywheel_minecraft_version = 1.20.1
flywheel_version = 0.6.11-13
emi_version = 1.1.18+1.20.1
jei_version = 15.2.0.22
