modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL="https://github.com/cassiancc/Create-Alloyed/issues"
license="MIT"

[[mods]]
modId = "alloyed"
version = "${mod_version}"
displayName = "Create: Alloyed"
logoFile= "alloyed.png"
credits="Original mod by Fortress Nebula, SpottyTheTurtle, and Bagels. Textures since 2.0 by asof."
authors="cassiancc, asof, Bagels"
description='''
A Create addon adding Bronze and Steel, both items used for compatibility and decoration!
'''

[[dependencies.alloyed]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alloyed]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alloyed]]
modId = "create"
type = "required"
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "alloyed.mixins.json"
